[[redirects]]
from = "/pet/:id"
to = "/pet?id=:id"
force = true
status = 200

[[redirects]]
from = "/*"
to = "/404.html"
status = 404

[[redirects]]
from = "/404.html"
to = "/404.html"
status = 404
force = true
